// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var One$AdventOfCode2019 = require("../../src/1/One.bs.js");

Jest.describe("One.fuel_from_moduleMass", (function (param) {
        Jest.test("12", (function (param) {
                return Jest.Expect[/* toBe */2](2, Jest.Expect[/* expect */0](One$AdventOfCode2019.fuel_from_moduleMass(12)));
              }));
        Jest.test("14", (function (param) {
                return Jest.Expect[/* toBe */2](2, Jest.Expect[/* expect */0](One$AdventOfCode2019.fuel_from_moduleMass(14)));
              }));
        Jest.test("1969", (function (param) {
                return Jest.Expect[/* toBe */2](654, Jest.Expect[/* expect */0](One$AdventOfCode2019.fuel_from_moduleMass(1969)));
              }));
        return Jest.test("100756", (function (param) {
                      return Jest.Expect[/* toBe */2](33583, Jest.Expect[/* expect */0](One$AdventOfCode2019.fuel_from_moduleMass(100756)));
                    }));
      }));

/*  Not a pure module */
