// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function add(x, y) {
  return x + y | 0;
}

function fuel_from_mass(mass) {
  return (mass / 3 | 0) - 2 | 0;
}

function fuelArray_from_massArray(param) {
  return param.reduce((function (acc, x) {
                return acc + fuel_from_mass(x) | 0;
              }), 0);
}

exports.add = add;
exports.fuel_from_mass = fuel_from_mass;
exports.fuelArray_from_massArray = fuelArray_from_massArray;
/* No side effect */
