// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Utils$AdventOfCode2019 = require("../Utils.bs.js");

function fuel_from_mass(mass) {
  return (mass / 3 | 0) - 2 | 0;
}

function fuelArray_from_massArray(param) {
  return param.reduce((function (acc, x) {
                return Utils$AdventOfCode2019.add(acc, fuel_from_mass(x));
              }), 0);
}

exports.fuel_from_mass = fuel_from_mass;
exports.fuelArray_from_massArray = fuelArray_from_massArray;
/* No side effect */
