// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function add(x, y) {
  return x + y | 0;
}

function fuel_from_mass_compounded(_mass, _$staropt$star, _param) {
  while(true) {
    var $staropt$star = _$staropt$star;
    var mass = _mass;
    var initFuel = $staropt$star !== undefined ? $staropt$star : 0;
    var fuel = (mass / 3 | 0) - 2 | 0;
    var match = fuel < 0;
    if (match) {
      return initFuel;
    } else {
      _param = /* () */0;
      _$staropt$star = initFuel + fuel | 0;
      _mass = fuel;
      continue ;
    }
  };
}

function fuelArray_from_massArray(param) {
  return param.reduce((function (acc, mass) {
                return acc + fuel_from_mass_compounded(mass, undefined, /* () */0) | 0;
              }), 0);
}

exports.add = add;
exports.fuel_from_mass_compounded = fuel_from_mass_compounded;
exports.fuelArray_from_massArray = fuelArray_from_massArray;
/* No side effect */
