// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");

function add(x, y) {
  return x + y | 0;
}

function head(x) {
  return Caml_array.caml_array_get(x, 0);
}

function nth(index, x) {
  return Caml_array.caml_array_get(x, index);
}

function update(index, value, x) {
  Caml_array.caml_array_set(x, index, value);
  return x;
}

exports.add = add;
exports.head = head;
exports.nth = nth;
exports.update = update;
/* No side effect */
